insert.max.retries: "3"
insert.mills.retries: "300"
update.max.retries: "3"
update.mills.retries: "300"
delete.max.retries: "3"
delete.mills.retries: "300"
delete.query: "delete from customer where id=:customerId"
update.query: "update customer set first_name=:firstName, last_name=:lastName, address=:address where id=:customerId"
insert.query: "insert into customer (first_name, last_name, address) values (:firstName, :lastName, :address)"
